import "./page.module.css";
import { Header } from "@/app/components/Header";
import { Footer } from "@/app/components/Footer";
import { Main } from "@/app/components/Main";

export const metadata = {
  title: "Index Page",
  description: "Generated by create next app",
};

export default function Index() {
  return (
    <>
      <Header />
      <Main page="index" />
      <Footer />
    </>
  );
}
